# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e9b029781db6d62afe9c49e63c6d3d30487288c2f787609d508f133a9269e526e337a933b5ad868ede0bad37c88001d91d0655b422d3a796bf6fa3b3fdb935f

test:
  secret_key_base: 5d717683021cbedd95870e1880571e63380e85fddb1c83da7a6c6a4f06016febe630fe866a94c0bd74faa9c5b5ee10b321f508e37830c9973a09ef9f4c4e2115

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
