# Those are real adresses that can be put on a map.
addresses = []
addresses << ["18 rue Condorcet", "93100"]
addresses << ["31 rue Victor. Masse", "75009"]
addresses << ["18 rue Duhesme", "75018"]
addresses << ["13 rue severo", "75014"]
addresses << ["rue Abel", "75012"]
addresses << ["69 boulevard Ornano", "75018"]
addresses << ["7 rue des petites écuries", "75010"]
addresses << ["7, place Marcel Paul", "75014"]
addresses << ["77 rue de Charonne", "75011"]
addresses << ["18 rue duhesme 75018 Paris", "75018"]
addresses << ["22 rue Guilleminot", "75014"]
addresses << ["9 rue des graviers", "92200"]
addresses << ["9 rue François Bonvin", "75015"]
addresses << ["34, rue Robert Lindet", "75015"]
addresses << ["70 rue du Vertbois", "75003"]
addresses << ["101 rue Lafayette", "75010"]
addresses << ["109 rue de l'Ouest", "75014"]
addresses << ["133 rue Championnet", "75018"]
addresses << ["22 Square Dunois", "75013"]
addresses << ["89 rue de Sèvres", "75006"]
addresses << ["80 rue Philippe de Girard", "75018"]
addresses << ["33, Bld de Vaugirard", "75015"]
addresses << ["28 rue de l'Aqueduc", "75010"]
addresses << ["42 BOULEVARD DE LA PAIX", "92400"]
addresses << ["9 rue Duc", "75018"]
addresses << ["47 Boulevard Beaumarchais", "75003"]
addresses << ["52, rue du Sergent Bobillot", "93100"]
addresses << ["32 rue du Capitaine Marchal", "75020"]
addresses << ["130 RUE DE PARIS", "92100"]
addresses << ["53ter avenue Raspail", "94100"]
addresses << ["25 rue Boyer", "75020"]
addresses << ["59, rue stephenson", "75018"]
addresses << ["7 rue Ernest Psichari", "75007"]
addresses << ["15 rue Bourseul", "75015"]
addresses << ["15bis/17 rue Jules Romain", "75019"]
addresses << ["181, rue du Château", "75014"]
addresses << ["57 rue carnot", "92100"]
addresses << ["280 rue Lecourbe", "75015"]
addresses << ["9 Rue Jean Rey", "75015"]
addresses << ["17 rue La Vieuville", "75018"]
addresses << ["41 rue de la Butte aux cailles ", "75013"]
addresses << ["rue Durantin", "75018"]
addresses << ["35 rue Saint Roch", "75001"]
addresses << ["123 rue de Tocqueville", "75017"]
addresses << ["35 rue Saint-Roch", "75001"]
addresses << ["Selon les activités", "75020"]
addresses << ["11 rue des Ponts Saint-Michel", "22200"]
addresses << ["9 place Marcel Paul", "75014"]
addresses << ["61 rue Violet", "75015"]
addresses << ["7 rue Vandrezanne", "75013"]
addresses << ["19, rue Rochebrune", "93100"]
addresses << ["65 Quai d'Orsay", "75007"]
addresses << ["320, Rue Saint-Honoré", "75001"]
addresses << ["", ""]
addresses << ["77 rue de Charonne", "75010"]
addresses << ["Rue de l'echiquier 75010 Paris", "75010"]
addresses << ["Maison des Associations - 22 rue Deparcieux", "75014"]
addresses << ["3bis, cité Bergère 75009 Paris", "75009"]
addresses << ["Rue des Martyrs", "75018"]
addresses << ["12 rue neuve de la chardonniere", "75018"]
addresses << ["cours des marechaux", "75012"]
addresses << ["33-35, rue de l'Amiral Mouchez", "75013"]
addresses << ["14 Rue michel le comte", "75010"]
addresses << ["12 rue parrot", "75012"]
addresses << ["62, rue Jean Jaurès", "94190"]
addresses << ["skype", "75014"]
addresses << ["Centre de danse du Marais", "75004"]
addresses << ["119 AVENUE DU GENERAL LECLERC", "75014"]
addresses << ["3 rue vicq d'azir", "75010"]
addresses << ["7, rue Robineau 75020", "75020"]
addresses << ["  Siege social  7 rue Jean Soubiran  Drancy", "93700"]
addresses << ["rue mathis", "75019"]
addresses << ["40 rue Quincampoix, 75004 Paris", "75004"]
addresses << ["13 rue Guyton de Morveau", "75013"]
addresses << ["116 rue de Lourmel", "75015"]
addresses << ["5 rue de Viroflay", "75015"]
addresses << ["101 bd Brune - PARIS 14e", "75014"]
addresses << ["93200 Saint Denis", "93200"]
addresses << ["Rue binet rue des amiraux", "75018"]
addresses << ["29 Rue de la liberation ", "91480"]
addresses << ["35 rue Saint Roch", "75001"]
addresses << ["10 rue de Paradis", "75010"]
addresses << ["41, rue du Temple", "75004"]
addresses << ["7/9 rue des petites écuries", "75020"]
addresses << ["2 bis rue pierre et marie curie", "92140"]
addresses << ["17, rue des Envierges", "75020"]
addresses << ["7 rue du cardinal Mercier", "75009"]
addresses << ["24 Rue de la Chine ", "75020"]
addresses << ["20, rue Lamarck", "75018"]
addresses << ["66bis rue Albert", "75018"]
addresses << ["17 avenue de paris", "94300"]
addresses << ["Rue Doudeauville", "75018"]
addresses << ["10 rue des Gardes", "75018"]
addresses << ["20 rue du retrait", "75020"]
addresses << ["6 Place Saint Michel", "75006"]
addresses << ["3, villa d'Orléans", "75014"]
addresses << ["84 BOULEVARD  BARBES", "75018"]
addresses << ["41 rue du Temple", "75004"]
addresses << ["15 rue Geoffroy L'Asnier", "75004"]
addresses << ["74 Av De Paris, Joinville", "94340"]

subjects  = ["Théâtre de rue", "Formation d'acteurs", "Clown", "Théâtre amateurs", "Diction & déclamation", "Variétés & studio", "Techniques vocales", "Comédies musicales", "Art dramatique", "Mise en scène & expression scénique", "Chant choral", "Spiritualités", "Estime de soi & confiance", "Massage", "Alimentation & diététique", "Yoga Nidra", "Yoga autres", "Relaxation & méditation", "Ateliers corps & mouvement", "Capoeira", "Coaching personnel", "Préparation à l'accouchement", "Femmes enceintes", "Sport & grossesse", "Respiration", "Yoga et randonnée", "Hatha yoga", "Wutao", "Lecture à voix haute", "Préparation à la scène / aux concerts", "Ecriture théâtrale", "Pratiques théâtrales mixtes", "Comédie & humour", "Improvisation théâtrale", "Dance floor & variétés", "Comédie musicale & chorégraphies", "Ragga, Dancehall & House", "Jazz, Street Jazz & Modern jazz", "Autres arts plastiques", "Dessin ou peinture d'après modèle vivant", "Aquarelle & lavis", "Copie de tableaux", "Croquis", "Découverte dessin & peinture", "Dessin à l'encre & plume", "Pastel", "Peinture", "Peinture à l'huile", "Peinture abstraite & contemporaine", "Peinture acrylique", "Dessin", "Crayon, mine & fusain", "Funambule & acrobate", "Mime", "Commedia dell'arte & masques", "Diverses danses classiques & contemporaines"]

lorems    = %w(Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod)
lorems   += %w(tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam)
lorems   += %w(quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo)
lorems   += %w(consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse)
lorems   += %w(cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non)
lorems   += %w(proident sunt in culpa qui officia deserunt mollit anim id est laborum.)

images_subjects = %w(abstract animals business cats city food nightlife fashion people nature sports technics transport)

addresses.each do |address|
  Structure.create(name:        Faker::Name.name,
                   description: lorems.sample(50).to_sentence,
                   zip_code:    address.last,
                   street:      address.first,
                   subject:     subjects.sample,
                   image_url:   "http://lorempixel.com/400/300/#{images_subjects.sample}/#{(1..10).to_a.sample}")
end
